function buses = casper_build_unified_buses()
%CASPER_BUILD_UNIFIED_BUSES Construct the unified bus dialect for Phase 0 visual model.
%
% Synopsis:
%   buses = casper_build_unified_buses()
%
% Returns a struct of six Simulink.Bus objects. Caller is responsible for
% placing them in the base workspace under matching names:
%
%   buses = casper_build_unified_buses();
%   for f = fieldnames(buses)', assignin('base', f{1}, buses.(f{1})); end
%
% Buses:
%   SensorInputBus  — unified sensor-input dialect (identical to TruthBus;
%                     renamed for the visual-model wiring so consumers don't
%                     need to know about the truth/sensor separation).
%   IMUOutputBus    — IMU subsystem output (LSM6DSO32 + ADXL372 sharing one
%                     bus; ADXL fields populated only post-launch).
%   BaroOutputBus   — MS5611 subsystem output.
%   MagOutputBus    — MMC5983MA + radio interference subsystem output.
%   GPSOutputBus    — MAX-M10M subsystem output.
%   EstimateBus     — combined attitude + ESKF estimator state.
%
% Used by:
%   T11 visual top-level model casper_sim_phase0.slx
%   T03 imu_block_visual.slx
%   T04/T05/T06 bus-adapter subsystems
%   T10 validation_block (interface unified from 14 inports → 3 bus inports)
%
% See plan: lets-first-get-started-gentle-newt.md "Bus design (foundation)".

    buses = struct();
    buses.SensorInputBus = build_sensor_input_bus();
    buses.IMUOutputBus   = build_imu_output_bus();
    buses.BaroOutputBus  = build_baro_output_bus();
    buses.MagOutputBus   = build_mag_output_bus();
    buses.GPSOutputBus   = build_gps_output_bus();
    buses.EstimateBus    = build_estimate_bus();
end

% =============================================================================

function bus = build_sensor_input_bus()
% Identical to TruthBus by design — renamed for visual-model clarity.
    fields = { ...
        {'pos_NED',          3, 'm',      'double', 'world-frame NED position'}, ...
        {'vel_NED',          3, 'm/s',    'double', 'world-frame NED velocity'}, ...
        {'accel_NED',        3, 'm/s^2',  'double', 'world-frame NED net accel (gravity-free)'}, ...
        {'quat_std',         4, '',       'double', 'body-to-NED quat scalar-first [w x y z]'}, ...
        {'omega_body_std',   3, 'rad/s',  'double', 'body-frame angular rate'}, ...
        {'time_s',           1, 's',      'double', 'simulation time'}, ...
        {'mach',             1, '',       'double', 'Mach number'}, ...
        {'air_density_kgm3', 1, 'kg/m^3', 'double', 'air density'}, ...
        {'air_temp_K',       1, 'K',      'double', 'air temperature'}, ...
        {'air_pressure_pa',  1, 'Pa',     'double', 'air pressure'} ...
    };
    bus = build_bus_from_fields_('SensorInputBus (unified truth→sensors)', fields);
end

function bus = build_imu_output_bus()
    fields = { ...
        {'accel_g_body_std',    3, 'g',   'double',  'LSM6DSO32 accel, body-std frame'}, ...
        {'gyro_dps_body_std',   3, 'dps', 'double',  'LSM6DSO32 gyro, body-std frame'}, ...
        {'temp_C',              1, 'degC','double',  'LSM6DSO32 temperature'}, ...
        {'data_ready',          1, '',    'boolean', 'LSM6DSO32 data-ready strobe'}, ...
        {'adxl_g_body_std',     3, 'g',   'double',  'ADXL372 high-g accel, body-std frame'}, ...
        {'adxl_fifo_active',    1, '',    'boolean', 'ADXL FIFO latch (alt > 5 m → true, one-way)'} ...
    };
    bus = build_bus_from_fields_('IMUOutputBus', fields);
end

function bus = build_baro_output_bus()
    fields = { ...
        {'press_pa',   1, 'Pa',   'double',  'MS5611 pressure'}, ...
        {'alt_m',      1, 'm',    'double',  'MS5611 decoded altitude (firmware formula)'}, ...
        {'temp_C',     1, 'degC', 'double',  'MS5611 temperature'}, ...
        {'data_ready', 1, '',     'boolean', 'MS5611 data-ready strobe'} ...
    };
    bus = build_bus_from_fields_('BaroOutputBus', fields);
end

function bus = build_mag_output_bus()
    fields = { ...
        {'field_uT_body_std', 3, 'uT', 'double',  'MMC5983MA calibrated field, body-std frame'}, ...
        {'raw18',             3, '',   'uint32',  'MMC5983MA 18-bit unsigned raw counts'}, ...
        {'radio_active',      1, '',   'boolean', 'Radio TX active flag (mag interference window)'}, ...
        {'data_ready',        1, '',   'boolean', 'MMC5983MA data-ready strobe'} ...
    };
    bus = build_bus_from_fields_('MagOutputBus', fields);
end

function bus = build_gps_output_bus()
    fields = { ...
        {'lat_deg7',   1, 'deg*1e-7', 'int32',   'MAX-M10M latitude (firmware NAV-PVT scale)'}, ...
        {'lon_deg7',   1, 'deg*1e-7', 'int32',   'MAX-M10M longitude (firmware NAV-PVT scale)'}, ...
        {'alt_mm',     1, 'mm',       'int32',   'MAX-M10M MSL altitude'}, ...
        {'vel_n_mms',  1, 'mm/s',     'int32',   'MAX-M10M N velocity'}, ...
        {'vel_e_mms',  1, 'mm/s',     'int32',   'MAX-M10M E velocity'}, ...
        {'vel_d_mms',  1, 'mm/s',     'int32',   'MAX-M10M D velocity'}, ...
        {'fix',        1, '',         'uint8',   'fix type (0 none / 2 / 3)'}, ...
        {'sv',         1, '',         'uint8',   'sat count'}, ...
        {'data_ready', 1, '',         'boolean', 'NAV-PVT data-ready strobe'} ...
    };
    bus = build_bus_from_fields_('GPSOutputBus', fields);
end

function bus = build_estimate_bus()
    fields = { ...
        {'state_x',         4, 'mixed', 'double',  'ESKF state [alt_m; vel_mps; ab_mps2; bb_m]'}, ...
        {'P_diag',          4, 'mixed', 'double',  'ESKF covariance diagonal'}, ...
        {'quat_fw',         4, '',      'double',  'attitude quaternion body-to-NAV (fw convention)'}, ...
        {'init_complete',   1, '',      'boolean', 'attitude static init complete'}, ...
        {'mach_gate',       1, '',      'boolean', 'ESKF Mach gate active'}, ...
        {'ungate_counter',  1, '',      'uint32',  'post-Mach un-gate recovery counter'} ...
    };
    bus = build_bus_from_fields_('EstimateBus', fields);
end

% =============================================================================

function bus = build_bus_from_fields_(description, fields)
% Generic Simulink.Bus constructor used by every bus above.
% fields cell: each entry {name, dims, units, datatype, description}.
    elems(numel(fields), 1) = Simulink.BusElement();
    for k = 1:numel(fields)
        e = Simulink.BusElement();
        e.Name           = fields{k}{1};
        e.Dimensions     = fields{k}{2};
        e.DataType       = fields{k}{4};
        e.SampleTime     = -1;
        e.Complexity     = 'real';
        e.DimensionsMode = 'Fixed';
        e.Description    = fields{k}{5};
        e.DocUnits       = fields{k}{3};
        elems(k) = e;
    end
    bus = Simulink.Bus();
    bus.Description = description;
    bus.Elements    = elems;
end
