% casper_sensor_params.m
%
% Single source of truth for C.A.S.P.E.R.-2 Phase 0 simulator runtime values.
% Each value is annotated with its firmware source file and line/define.
% Do not hand-edit. Regenerate via T02 if firmware changes.
%
% Generated by T02 (sensor parameter library task).
% Firmware git ref: 80210b26318aec39f28818b6985ca2098afe2b9e
%
% Naming convention: structs are capitalized (Sim, IMU, ADXL, Baro, Mag, GPS,
% Estimator, Attitude, GyroTempCal, Radio, FSM, Validation). Physical
% quantities carry unit suffixes (alt_m, vel_mps, accel_g, mag_uT, time_s).
%
% Run this script (no arguments) at the start of every Phase 0 sim session
% to populate the base workspace. Downstream tasks T03..T11 must reference
% these struct fields rather than hard-coding numerical values.

% ===== Sim global =====
Sim = struct();
Sim.SolverDt        = 1e-4;         % s, 10 kHz fixed-step ode4 (ARCHITECTURE.md §2)
Sim.Seed            = 20260519;     % default seed (ARCHITECTURE.md §6)
Sim.GravityMps2     = 9.80665;      % m/s^2, casper_ekf.c #define G_ACCEL
Sim.FirmwareCommit  = '80210b26318aec39f28818b6985ca2098afe2b9e';

% ===== IMU (LSM6DSO32) =====
IMU = struct();
IMU.Rate_Hz             = 833;          % CTRL1_XL=0x74, lsm6dso32.c init()
IMU.AccelRange_g        = 32;           % CTRL1_XL=0x74 (FS=01b => +/-32g)
IMU.AccelScale_gPerLSB  = 0.000976;     % lsm6dso32.c read(): raw * 0.000976f
IMU.GyroRange_dps       = 2000;         % CTRL2_G=0x7C (FS=110b => +/-2000dps)
IMU.GyroScale_dpsPerLSB = 0.070;        % lsm6dso32.c read(): raw * 0.070f
IMU.TempScale_LSBperC   = 256;          % lsm6dso32.c: temp_c = raw/256 + 25
IMU.TempOffset_C        = 25;           % lsm6dso32.c: temp_c = raw/256 + 25
IMU.HighPerf            = true;         % CTRL6_C=0x00, CTRL7_G=0x00 (high-perf mode)
IMU.IntPin              = 'INT2_DATA_READY'; % INT2_CTRL = 0x01 (accel data-ready)

% ===== ADXL372 (high-G) =====
ADXL = struct();
ADXL.Range_g                = 200;      % adxl372.h: +/-200g, 12-bit
ADXL.Scale_gPerLSB          = 0.1;      % adxl372.h: 100 mg/LSB
ADXL.RatePreLaunch_Hz       = 400;      % adxl372.c init(): ODR_400HZ
ADXL.RatePostLaunch_Hz      = 800;      % adxl372_fifo_init() called with ODR_800HZ
ADXL.BandwidthPreLaunch_Hz  = 200;      % adxl372.c init(): BW_200HZ
ADXL.BandwidthPostLaunch_Hz = 400;      % adxl372_fifo_init() pairs ODR_800 -> BW_400

% ===== Baro (MS5611) =====
Baro = struct();
Baro.Rate_Hz            = 100;          % ms5611.c non-blocking tick, ~100 Hz effective
Baro.OSR                = 4096;         % ms5611.c init(): dev->osr = MS5611_OSR_4096
Baro.ConversionDelay_ms = 9.1;          % ms5611.h: OSR_4096 = 9.1 ms (per datasheet)
Baro.PressureRes_Pa     = 1;            % 24-bit ADC ~ 1 Pa resolution
Baro.TempRes_C          = 0.01;         % ms5611.h: temperature scaled 0.01 deg C
Baro.SeaLevelRef_hPa    = 1013.25;      % ms5611.c get_altitude() default ref
Baro.AltitudeCoeff      = 44307.694;    % ms5611.c get_altitude(): 44307.694f
Baro.AltitudeExponent   = 0.190284;     % ms5611.c get_altitude(): 0.190284f

% ===== Mag (MMC5983MA) =====
Mag = struct();
Mag.Rate_Hz             = 100;          % mmc5983ma.c init(): CM_100HZ
Mag.RangeGauss          = 8;            % mmc5983ma.h: +/-8 Gauss
Mag.Bits                = 18;           % mmc5983ma.h: 18-bit unsigned
Mag.OffsetCounts        = 131072;       % mmc5983ma.h MMC5983MA_18BIT_OFFSET (2^17)
Mag.ScaleCountsPerGauss = 16384;        % mmc5983ma.h MMC5983MA_18BIT_SCALE
Mag.Bandwidth_Hz        = 800;          % mmc5983ma.c init(): BW_800HZ
Mag.AutoSetReset        = true;         % mmc5983ma.c init(): CTRL0_AUTO_SR_EN

% Calibration vectors (mag_cal.c static arrays)
Mag.HardIron_uT = [ -9.082933;  -23.520703;  -18.099732 ];   % mag_cal.c mag_hard_iron[]
Mag.SoftIron    = [  0.777972,  -0.017063,  -0.010798; ...
                    -0.017063,   0.806570,   0.014623; ...
                    -0.010798,   0.014623,   0.784949 ];      % mag_cal.c mag_soft_iron[][]
Mag.AxisFlipSign     = [-1; -1; -1];        % mag_cal.c tick: mx,my,mz = -raw_x,-raw_y,-raw_z
Mag.ExpectedMag_uT   = 40.18;               % mag_cal.h MAG_CAL_EXPECTED_MAG = 40.1800f
Mag.NoiseTauSec      = 0.160;               % AR(1) correlation time (memory note)
Mag.NoiseStd_uT      = 0.5;                 % per-axis 1-sigma placeholder (refine later)

% ===== Mag->Radio interference (placeholder, Phase 0 only) =====
Mag.RadioInterfActive = true;
Mag.RadioSpikeAmp_uT  = 10.0;       % +/-10 uT rectangular pulse (placeholder)
Mag.RadioTXAirtime_s  = 0.015;      % SF7 ~ 15 ms airtime
Mag.RadioTXPeriod_s   = 0.100;      % 10 Hz TX cadence

% ===== GPS (MAX-M10M) =====
GPS = struct();
GPS.Rate_Hz                  = 10;       % max_m10m.c init: CFG_RATE_MEAS=100ms => 10Hz
GPS.PositionCEP_Horizontal_m = 1.5;      % datasheet typical (open sky)
GPS.VelocityNoise_mps        = 0.05;     % datasheet typical
GPS.Latency_s                = 0.1;      % datasheet typical 100 ms
GPS.COCOMVelThreshold_mps    = 500;      % COCOM limit (informational)
GPS.COCOMAltThreshold_m      = 18000;    % COCOM limit (informational)
GPS.Protocol                 = 'UBX-NAV-PVT';  % max_m10m.c: CFG_MSGOUT_UBX_NAV_PVT_I2C

% ===== Estimator (4-state vertical EKF, stripped per ARCHITECTURE.md §7) =====
Estimator = struct();
Estimator.PredictRate_Hz    = 416;            % 1 / EKF_DT
Estimator.Dt                = 0.0024;         % casper_ekf.c #define EKF_DT
Estimator.G                 = 9.80665;        % casper_ekf.c #define G_ACCEL
Estimator.P0_Alt            = 0.1;            % casper_ekf.c #define P0_ALT (m^2)
Estimator.P0_Vel            = 0.001;          % casper_ekf.c #define P0_VEL ((m/s)^2)
Estimator.P0_AccelBias      = 0.025;          % casper_ekf.c #define P0_ACCEL_BIAS
Estimator.P0_BaroBias       = 0.75;           % casper_ekf.c #define P0_BARO_BIAS
Estimator.AccelVRW          = 2.162545e-3;    % casper_ekf.c #define ACCEL_VRW
Estimator.AccelBiSigma      = 1.953783e-4;    % casper_ekf.c #define ACCEL_BI_SIGMA
Estimator.BaroBiSigma       = 1.0e-3;         % casper_ekf.c #define BARO_BI_SIGMA
Estimator.R_Baro            = 0.5;            % casper_ekf.c #define R_BARO (m^2)
Estimator.R_Zupt            = 6.15e-6;        % casper_ekf.c #define R_ZUPT
Estimator.BaroGateK2        = 25.0;           % casper_ekf.c #define BARO_GATE_K2 (5-sigma^2)
Estimator.PFloorBaroBias    = 0.01;           % casper_ekf.c #define P_FLOOR_BARO_BIAS
Estimator.MachGateOn        = 0.40;           % casper_ekf.c #define MACH_GATE_ON
Estimator.MachGateOff       = 0.35;           % casper_ekf.c #define MACH_GATE_OFF
Estimator.R_BaroUngate      = 50.0;           % casper_ekf.c #define R_BARO_UNGATE
Estimator.N_UngateSteps     = 10;             % casper_ekf.c #define N_UNGATE_STEPS
Estimator.P_UngateAccelBias = 1.0;            % casper_ekf.c #define P_UNGATE_ACCEL_BIAS
Estimator.P_UngateBaroBias  = 10.0;           % casper_ekf.c #define P_UNGATE_BARO_BIAS
Estimator.ZuptThreshold     = 0.3;            % casper_ekf.h EKF_ZUPT_THRESHOLD (m/s^2)
Estimator.H_Baro            = [1, 0, 0, 1];   % casper_ekf.c update_baro: H = [1,0,0,1]
Estimator.H_Zupt            = [0, 1, 0, 0];   % casper_ekf.c update_zupt: H = [0,1,0,0]

% ===== Attitude estimator (Mahony + RK4) =====
% NOTE: Mahony gains are sourced from main.c casper_att_config_t {} initializer
% (main.c lines 384-392), NOT from FIRMWARE_CONSTANTS.md typical-defaults table.
% Per CLAUDE.md "Firmware is canonical": flight values override the doc.
Attitude = struct();
Attitude.GyroArw_radSqrtS    = [6.08e-5; 4.92e-5; 6.73e-5];  % casper_attitude.c att_init()
Attitude.GyroLpfCutoff_Hz    = 50.0;       % main.c att_cfg.gyro_lpf_cutoff_hz = 50.0f
Attitude.MagUpdateRate_Hz    = 10.0;       % main.c att_cfg.mag_update_hz = 10.0f
Attitude.Kp_Grav             = 10.0;       % main.c att_cfg.Kp_grav = 10.0f
Attitude.Kp_MagPad           = 0.0;        % main.c att_cfg.Kp_mag_pad = 0.0f
Attitude.Kp_MagFlight        = 0.0;        % main.c att_cfg.Kp_mag_flight = 0.0f
Attitude.Ki                  = 0.1;        % main.c att_cfg.Ki = 0.1f
Attitude.LaunchAccel_g       = 3.0;        % main.c att_cfg.launch_accel_g = 3.0f
Attitude.StaticInitSamples   = 500;        % casper_attitude.c STATIC_INIT_MAG_SAMPLES
Attitude.StaticInitTimeout_s = 10.0;       % casper_attitude.c STATIC_INIT_TIMEOUT_S
Attitude.HeadingSigmaFloor_rad = 0.01;     % casper_attitude.c HEADING_SIGMA_FLOOR
Attitude.BiasGyroThresh_radps  = 0.035;    % casper_attitude.c BIAS_GYRO_THRESH
Attitude.BiasEmaInvTau_perS    = 0.2;      % casper_attitude.c BIAS_EMA_INV_TAU

% ===== Gyro temperature (informational, NOT applied in Phase 0) =====
GyroTempCal = struct();
GyroTempCal.T0_C    =  15.250;        % temp_cal_coeffs.h GYRO_TC_T0
GyroTempCal.Slope_X = -5.2144e-4;     % temp_cal_coeffs.h GYRO_TC_SLOPE_X (rad/s/degC)
GyroTempCal.Slope_Y =  2.2923e-4;     % temp_cal_coeffs.h GYRO_TC_SLOPE_Y
GyroTempCal.Slope_Z =  0.0;           % temp_cal_coeffs.h GYRO_TC_SLOPE_Z (zeroed)

% ===== Radio =====
Radio = struct();
Radio.TX_Period_s        = 0.100;     % radio_config.h RADIO_TX_PERIOD_MS = 100
Radio.TX_Timeout_s       = 0.200;     % radio_config.h RADIO_TX_TIMEOUT_MS = 200
Radio.ProfileA_SF        = 7;         % radio_config.c RADIO_PROFILE_A.sf
Radio.ProfileA_BW_Hz     = 250000;    % radio_config.c RADIO_PROFILE_A.bw_hz
Radio.ProfileA_CR        = 5;         % radio_config.c RADIO_PROFILE_A.cr (4/5)
Radio.ProfileA_Airtime_s = 0.015;     % SF7@250kHz, ~17B payload: 2^SF/BW*30sym ~ 15 ms
Radio.ProfileB_SF        = 8;         % radio_config.c RADIO_PROFILE_B.sf
Radio.ProfileB_BW_Hz     = 250000;    % radio_config.c RADIO_PROFILE_B.bw_hz
Radio.ProfileB_CR        = 5;         % radio_config.c RADIO_PROFILE_B.cr (4/5)
Radio.ProfileB_Airtime_s = 0.028;     % SF8@250kHz, ~17B payload ~ 28 ms
Radio.Frequency_Hz       = 868000000; % radio_config.c freq_hz
Radio.TXPower_dBm        = 20;        % radio_config.c tx_power_dbm = +20
Radio.SyncWord           = uint8(hex2dec('12'));  % radio_config.c sync_word = 0x12
Radio.Preamble_Symbols   = 8;         % radio_config.c preamble = 8
Radio.SwitchAlt_m        = 20000;     % radio_config.h RADIO_PROFILE_SWITCH_ALT_M
Radio.SwitchVel_mps      = 500;       % radio_config.h RADIO_PROFILE_SWITCH_VEL_MPS

% ===== FSM thresholds (informational, no FSM in Phase 0) =====
FSM = struct();
FSM.LaunchAccel_g        = 2.0;       % fsm_types.h FSM_LAUNCH_ACCEL_G
FSM.LaunchAccelDwell_ms  = 100;       % fsm_types.h FSM_LAUNCH_ACCEL_DWELL_MS
FSM.LaunchVel_mps        = 15.0;      % fsm_types.h FSM_LAUNCH_VEL_MPS
FSM.BurnoutAccel_g       = 0.0;       % fsm_types.h FSM_BURNOUT_ACCEL_G
FSM.BurnoutDwell_ms      = 100;       % fsm_types.h FSM_BURNOUT_DWELL_MS
FSM.SustainAccel_g       = 3.0;       % fsm_types.h FSM_SUSTAIN_ACCEL_G
FSM.SustainDwell_ms      = 100;       % fsm_types.h FSM_SUSTAIN_DWELL_MS
FSM.ApogeeVel_mps        = 0.0;       % fsm_types.h FSM_APOGEE_VEL_MPS
FSM.ApogeeVelDwell_ms    = 25;        % fsm_types.h FSM_APOGEE_VEL_DWELL_MS
FSM.ApogeeMinFlight_s    = 5.0;       % fsm_types.h FSM_APOGEE_MIN_FLIGHT_S
FSM.LandedVel_mps        = 1.0;       % fsm_types.h FSM_LANDED_VEL_MPS
FSM.LandedAltDelta_m     = 2.0;       % fsm_types.h FSM_LANDED_ALT_DELTA_M
FSM.LandedDwell_ms       = 3000;      % fsm_types.h FSM_LANDED_DWELL_MS

% ===== Telemetry encoding scales (tlm_types.h, informational) =====
Telemetry = struct();
Telemetry.AltScale_m         = 0.01;  % tlm_types.h ALT_SCALE_M (u24, max 167.7 km)
Telemetry.VelScale_dms       = 0.1;   % tlm_types.h VEL_SCALE_DMS (i16, 0.1 m/s)
Telemetry.TimeScale_100ms    = 0.1;   % tlm_types.h TIME_SCALE_100MS
Telemetry.BattOffset_V       = 6.0;   % tlm_types.h BATT_OFFSET_V
Telemetry.BattStep_V         = 0.012; % tlm_types.h BATT_STEP_V

% ===== Validation tolerances (Phase 0 trust gate placeholders) =====
Validation = struct();
Validation.ApogeeError_m        = 10.0;   % m, |sim_apogee - truth_apogee|
Validation.AttitudeRmsError_deg = 1.0;    % deg RMS
Validation.BurnoutVelRms_mps    = 2.0;    % m/s RMS

% Confirm population to caller.
fprintf('[T02] casper_sensor_params loaded. Firmware ref: %s\n', Sim.FirmwareCommit);

% Eof
