function lib_path = build_frame_switch_block(varargin)
%BUILD_FRAME_SWITCH_BLOCK Programmatically construct the frame_switch library.
%
% Synopsis:
%   lib_path = build_frame_switch_block()
%   lib_path = build_frame_switch_block('LibPath', '/abs/path/lib.slx')
%
% Creates (or replaces) a Simulink library at
% <T07 build dir>/frame_switch_block.slx containing a subsystem
% 'frame_switch' with three independent MATLAB Function block paths:
%   - nav_switch  : 3x1 vec_NED  -> 3x1 vec_Zup
%   - body_switch : 3x1 vec_std  -> 3x1 vec_fw
%   - quat_switch : 4x1 q_std    -> 4x1 q_fw
%
% Each block inlines the math (no struct lookup at run time) per
% T07 spec section 9 "no allocations, no loops".
%
% Outputs:
%   lib_path : char, absolute path to the saved .slx library
%
% Source firmware reference:
%   None (HIL boundary; defined by T07 spec).

    p = inputParser();
    addParameter(p, 'LibPath', '', @(x) ischar(x) || isstring(x));
    parse(p, varargin{:});
    lib_path = char(p.Results.LibPath);

    if isempty(lib_path)
        here = fileparts(mfilename('fullpath'));
        lib_path = fullfile(here, 'frame_switch_block.slx');
    end

    lib_name = 'frame_switch_block';
    sub_name = 'frame_switch';

    if bdIsLoaded(lib_name)
        close_system(lib_name, 0);
    end

    if isfile(lib_path)
        % Remove any stale lib file to ensure deterministic regeneration.
        delete(lib_path);
    end

    new_system(lib_name, 'Library');
    load_system(lib_name);

    sub_path = [lib_name '/' sub_name];
    add_block('built-in/Subsystem', sub_path);
    set_param(sub_path, 'Position', [60 60 540 480]);

    % -----------------------------------------------------------------
    % Inport / Outport / MATLAB Function -- nav switch
    % -----------------------------------------------------------------
    in_nav  = [sub_path '/vec_NED'];
    out_nav = [sub_path '/vec_Zup'];
    fcn_nav = [sub_path '/nav_switch'];
    add_block('built-in/Inport',  in_nav);   set_param(in_nav,  'Port', '1', 'Position', [40 60 70 80]);
    add_block('simulink/User-Defined Functions/MATLAB Function', fcn_nav);
    set_param(fcn_nav, 'Position', [150 50 320 100]);
    add_block('built-in/Outport', out_nav);  set_param(out_nav, 'Port', '1', 'Position', [380 60 410 80]);
    set_matlab_fcn(fcn_nav, [ ...
        'function vec_Zup = nav_switch(vec_NED)\n', ...
        '%#codegen\n', ...
        'vec_Zup = zeros(3,1);\n', ...
        'vec_Zup(1) =  vec_NED(1);\n', ...
        'vec_Zup(2) =  vec_NED(2);\n', ...
        'vec_Zup(3) = -vec_NED(3);\n', ...
        'end\n']);
    add_line(sub_path, 'vec_NED/1',    'nav_switch/1', 'autorouting', 'on');
    add_line(sub_path, 'nav_switch/1', 'vec_Zup/1',    'autorouting', 'on');

    % -----------------------------------------------------------------
    % Inport / Outport / MATLAB Function -- body switch
    % -----------------------------------------------------------------
    in_body  = [sub_path '/vec_std'];
    out_body = [sub_path '/vec_fw'];
    fcn_body = [sub_path '/body_switch'];
    add_block('built-in/Inport',  in_body);  set_param(in_body,  'Port', '2', 'Position', [40 180 70 200]);
    add_block('simulink/User-Defined Functions/MATLAB Function', fcn_body);
    set_param(fcn_body, 'Position', [150 170 320 220]);
    add_block('built-in/Outport', out_body); set_param(out_body, 'Port', '2', 'Position', [380 180 410 200]);
    set_matlab_fcn(fcn_body, [ ...
        'function vec_fw = body_switch(vec_std)\n', ...
        '%#codegen\n', ...
        'vec_fw = zeros(3,1);\n', ...
        'vec_fw(1) =  vec_std(2);\n', ...
        'vec_fw(2) =  vec_std(1);\n', ...
        'vec_fw(3) = -vec_std(3);\n', ...
        'end\n']);
    add_line(sub_path, 'vec_std/1',     'body_switch/1', 'autorouting', 'on');
    add_line(sub_path, 'body_switch/1', 'vec_fw/1',      'autorouting', 'on');

    % -----------------------------------------------------------------
    % Inport / Outport / MATLAB Function -- quat switch
    % -----------------------------------------------------------------
    in_q  = [sub_path '/q_std'];
    out_q = [sub_path '/q_fw'];
    fcn_q = [sub_path '/quat_switch'];
    add_block('built-in/Inport',  in_q);  set_param(in_q,  'Port', '3', 'Position', [40 300 70 320]);
    add_block('simulink/User-Defined Functions/MATLAB Function', fcn_q);
    set_param(fcn_q, 'Position', [150 290 320 340]);
    add_block('built-in/Outport', out_q); set_param(out_q, 'Port', '3', 'Position', [380 300 410 320]);

    quat_body = [ ...
        'function q_fw = quat_switch(q_std)\n', ...
        '%#codegen\n', ...
        '% Hamilton scalar-first body-to-nav quaternion frame switch.\n', ...
        '% Composes T_nav = diag(1,1,-1) on the nav side and the body\n', ...
        '% permutation R_body = [0 1 0;1 0 0;0 0 -1] on the body side.\n', ...
        'q = q_std(:);\n', ...
        'nq = sqrt(q(1)*q(1) + q(2)*q(2) + q(3)*q(3) + q(4)*q(4));\n', ...
        'if nq < 1e-12\n', ...
        '    q_fw = [1;0;0;0];\n', ...
        '    return;\n', ...
        'end\n', ...
        'q = q ./ nq;\n', ...
        'w = q(1); x = q(2); y = q(3); z = q(4);\n', ...
        '% q -> DCM (body_std -> NED)\n', ...
        'C = zeros(3,3);\n', ...
        'C(1,1) = 1 - 2*(y*y + z*z); C(1,2) = 2*(x*y - z*w); C(1,3) = 2*(x*z + y*w);\n', ...
        'C(2,1) = 2*(x*y + z*w);     C(2,2) = 1 - 2*(x*x + z*z); C(2,3) = 2*(y*z - x*w);\n', ...
        'C(3,1) = 2*(x*z - y*w);     C(3,2) = 2*(y*z + x*w);     C(3,3) = 1 - 2*(x*x + y*y);\n', ...
        '% C_fw = T_nav_quat * C * R_body''\n', ...
        '%   T_nav_quat = [0 1 0; 1 0 0; 0 0 -1]  (proper, det = +1)\n', ...
        '%   R_body     = [0 1 0; 1 0 0; 0 0 -1]  (proper, det = +1)\n', ...
        '% T_nav_quat swaps row 1<->2 and flips row 3;\n', ...
        '% R_body''   swaps col 1<->2 and flips col 3.\n', ...
        'Cf = zeros(3,3);\n', ...
        'Cf(1,1) =  C(2,2); Cf(1,2) =  C(2,1); Cf(1,3) = -C(2,3);\n', ...
        'Cf(2,1) =  C(1,2); Cf(2,2) =  C(1,1); Cf(2,3) = -C(1,3);\n', ...
        'Cf(3,1) = -C(3,2); Cf(3,2) = -C(3,1); Cf(3,3) =  C(3,3);\n', ...
        '% Cf -> Hamilton quaternion (Shepperd, scalar-first, w>=0)\n', ...
        'tr = Cf(1,1) + Cf(2,2) + Cf(3,3);\n', ...
        'qw = 1; qx = 0; qy = 0; qz = 0;\n', ...
        'if tr > 0\n', ...
        '    s = sqrt(tr + 1.0) * 2.0;\n', ...
        '    qw = 0.25 * s;\n', ...
        '    qx = (Cf(3,2) - Cf(2,3)) / s;\n', ...
        '    qy = (Cf(1,3) - Cf(3,1)) / s;\n', ...
        '    qz = (Cf(2,1) - Cf(1,2)) / s;\n', ...
        'elseif (Cf(1,1) > Cf(2,2)) && (Cf(1,1) > Cf(3,3))\n', ...
        '    s = sqrt(1.0 + Cf(1,1) - Cf(2,2) - Cf(3,3)) * 2.0;\n', ...
        '    qw = (Cf(3,2) - Cf(2,3)) / s;\n', ...
        '    qx = 0.25 * s;\n', ...
        '    qy = (Cf(1,2) + Cf(2,1)) / s;\n', ...
        '    qz = (Cf(1,3) + Cf(3,1)) / s;\n', ...
        'elseif Cf(2,2) > Cf(3,3)\n', ...
        '    s = sqrt(1.0 + Cf(2,2) - Cf(1,1) - Cf(3,3)) * 2.0;\n', ...
        '    qw = (Cf(1,3) - Cf(3,1)) / s;\n', ...
        '    qx = (Cf(1,2) + Cf(2,1)) / s;\n', ...
        '    qy = 0.25 * s;\n', ...
        '    qz = (Cf(2,3) + Cf(3,2)) / s;\n', ...
        'else\n', ...
        '    s = sqrt(1.0 + Cf(3,3) - Cf(1,1) - Cf(2,2)) * 2.0;\n', ...
        '    qw = (Cf(2,1) - Cf(1,2)) / s;\n', ...
        '    qx = (Cf(1,3) + Cf(3,1)) / s;\n', ...
        '    qy = (Cf(2,3) + Cf(3,2)) / s;\n', ...
        '    qz = 0.25 * s;\n', ...
        'end\n', ...
        'q_fw = [qw; qx; qy; qz];\n', ...
        'nf = sqrt(q_fw(1)^2 + q_fw(2)^2 + q_fw(3)^2 + q_fw(4)^2);\n', ...
        'if nf > 0\n', ...
        '    q_fw = q_fw ./ nf;\n', ...
        'end\n', ...
        'if q_fw(1) < 0\n', ...
        '    q_fw = -q_fw;\n', ...
        'end\n', ...
        'end\n'];
    set_matlab_fcn(fcn_q, quat_body);

    add_line(sub_path, 'q_std/1',      'quat_switch/1', 'autorouting', 'on');
    add_line(sub_path, 'quat_switch/1', 'q_fw/1',       'autorouting', 'on');

    % Lock + save library
    set_param(lib_name, 'Lock', 'on');
    save_system(lib_name, lib_path);
    close_system(lib_name, 0);

    fprintf('[build_frame_switch_block] wrote %s\n', lib_path);
end

% =========================================================================
function set_matlab_fcn(block_path, script_text)
%SET_MATLAB_FCN Replace the script inside a MATLAB Function block.
    rt = sfroot();
    block_handle = getSimulinkBlockHandle(block_path);
    if block_handle == -1
        error('set_matlab_fcn:no_block', 'block not found: %s', block_path);
    end
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', block_path);
    if isempty(chart)
        % Fall back to a fresh-block traversal.
        sfblock = rt.find('-isa', 'Stateflow.EMChart');
        for k = 1:numel(sfblock)
            if strcmp(sfblock(k).Path, block_path)
                chart = sfblock(k);
                break;
            end
        end
    end
    if isempty(chart)
        error('set_matlab_fcn:no_chart', ...
              'MATLAB Function chart not found at %s', block_path);
    end
    chart.Script = sprintf(script_text);
end
